-- Create View SALES ORDER DETAIL -- 

CREATE OR REPLACE VIEW ORDER_XFRM.V_SALES_ORDER_DETAIL (ORDER_ID, ORDER_DATE, CUSTOMER_ID, ITEM_ID, QTY,
Total_Amount, CREATE_DATE, CREATE_USER, PRICE) AS 
SELECT 
ORDER_ID, ORDER_DATE, CUSTOMER_ID, ITEM_ID, QTY, 
PRICE, TOTAL_AMOUNT, CREATE_DATE, CREATE_USER
FROM order_process.ORDER_BASE.T_SALES_ORDER_DETAIL;