-- Create View PROMOTION --

CREATE OR REPLACE VIEW ORDER_XFRM.V_PROMOTION (
PROMOTION_ID, CUSTOMER_CATEGORY, PROMOTION_TYPE, PROMOTION_VALUE, COMMENT)
AS  SELECT PROMOTION_ID, CUSTOMER_CATEGORY, PROMOTION_TYPE,
PROMOTION_VALUE, COMMENTS FROM ORDER_BASE.T_PROMOTION;