-- Create View SALES ORDER HEADER -- 

CREATE OR REPLACE VIEW ORDER_XFRM.V_SALES_ORDER_HDR (ORDER_ID, ORDER_DATE, STATUS, CUSTOMER_ID, ITEM_COUNT, TOTAL_AMOUNT, DISCOUNT, COUPON_CODE, CREATE_DATE, CREATE_USER) AS 
SELECT ORDER_ID, ORDER_DATE, STATUS, CUSTOMER_ID, 
ITEM_COUNT, TOTAL_AMOUNT, DISCOUNT, COUPON_CODE,
CREATE_DATE, CREATE_USER FROM order_process.ORDER_BASE.T_SALES_ORDER_HEADER 
WHERE order_date > CURRENT_DATE;
