-- Create Table Sales Order Detail -- 

CREATE OR REPLACE TABLE ORDER_BASE.T_SALES_ORDER_DETAIL (
    ORDER_ID VARCHAR(10) NOT NULL,
    ORDER_DATE DATE,
    CUSTOMER_ID VARCHAR(10),
    ITEM_ID VARCHAR(10),
    QTY INTEGER,
    PRICE NUMBER(12,2),
    TOTAL_AMOUNT NUMBER(12,2),
    CREATE_DATE DATE,
    CREATE_USER VARCHAR(10),
    PRIMARY KEY (ITEM_ID),
    CONSTRAINT ITEM_ID UNIQUE ITEM_ID
);
