-- Create Table SALES ORDER HEADER --

CREATE OR REPLACE TABLE ORDER_BASE.T_SALES_ORDER_HEADER (
ORDER_ID  VARCHAR(10) PRIMARY KEY NOT NULL,
ORDER_DATE DATE,
STATUS VARCHAR(10),
CUSTOMER_ID VARCHAR(10),
ITEM_COUNT INTEGER,
TOTAL_AMOUNT number(12,2),
DISCOUNT Number(12,2),
COUPON_CODE Varchar(10),
CREATE_DATE DATE,
CREATE_USER VARCHAR(10),
UNIQUE(ORDER_ID) ENFORCED
);