-- Create Table Promotion --

CREATE OR REPLACE TABLE ORDER_BASE.T_PROMOTION (
PROMOTION_ID VARCHAR(10) UNIQUE,
CUSTOMER_CATEGORY VARCHAR(10),
PROMOTION_TYPE VARCHAR(10),
PROMOTION_VALUE	NUMBER(10,2),
COMMENTS	VARCHAR(20),
PRIMARY KEY(PROMOTION_ID)
);
